#!/bin/sh

set -eu

ANSIBLE_VERSION="${ANSIBLE_VERSION:-2.2.1.0}"

DEBIAN_FRONTEND=noninteractive apt-get -yq install build-essential python-dev python-virtualenv git

[ ! -f "/tmp/venv/bin/activate" ] && virtualenv /tmp/venv

. /tmp/venv/bin/activate && trap "deactivate" 0

pip install "ansible==${ANSIBLE_VERSION}"
