#!/bin/sh

set -eu

ROLES_VERSION="${ROLES_VERSION:-stable}"

. /tmp/venv/bin/activate && trap "deactivate" 0

ansible-galaxy install --force --roles-path /etc/ansible "git+https://gitea.evolix.org/evolix/ansible-roles.git,${ROLES_VERSION},roles"
