#!/bin/sh

set -eu

useradd --user-group --create-home --shell /bin/bash vagrant
usermod -G sudo vagrant
umask 0077
mkdir /home/vagrant/.ssh
wget --output-document=/home/vagrant/.ssh/authorized_keys 'https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant.pub'
chown --recursive vagrant:vagrant /home/vagrant/.ssh
